### ISSUE TITLE
Diagnostics are randomly sorted by severity

### ISSUE THREAD

**Issue by toyboot4e** [gagbo/consult-lsp#21] opened 2021-10-24 04:42 UTC
Hi :wave: I'm using `consult-lsp` everyday. Thank you for sharing it!

It [looks like][L] `consult-lsp` tries to sort flatten diagnostics by severity. So the order would be: error, warning, info and hints. But in the README pic, it's warning, eror and then hints. So the sort might not be working as expected.

On my computer, the order often changes and here's an example:

[L]: https://github.com/gagbo/consult-lsp/blob/main/consult-lsp.el#L151

<img width="1082" alt="diags" src="https://user-images.githubusercontent.com/47905926/138580978-3a1e1b1c-7924-4839-ae92-82620ed72859.png">

And another after meaningless change and saving:

<img width="600" alt="diag-2" src="https://user-images.githubusercontent.com/47905926/138581093-1c0cbe73-fe37-48a9-b623-c1453a7b70a5.png">

**Comment by minad** [comment] 2021-11-03 11:23
Unrelated to this issue, but the formatting could profit from some polishing: space/alignment of error/warn/hint, no colon after the line number, general alignment, ...

**Comment by gagbo** [comment] 2021-11-03 11:59
Fair enough, there's one part that should probably be fixed in consult though

**Comment by gagbo** [comment] 2021-11-03 12:33
Coming back to the original issue: @toyboot4e are you using Selectrum or Vertico (or something else, ido ?) there ? I remembered having the issue at some point, and trying to investigate a bit now, I actually can't reproduce it (with vertico), I'll keep looking for it though

**Comment by gagbo** [comment] 2021-11-03 13:02
Also :

- does the reordering happen if you have the cursor on a line where there's already a `hint` or `warning` ?
- does the reordering happen if you open `consult-lsp-diagnostics` after having selected a `hint` or a `warning` in a previous `consult-lsp-diagnostics` call ?

**Comment by toyboot4e** [comment] 2021-11-03 13:24
> are you using Selectrum or Vertico 

I'm using consult, vertico, marginalia, embark and embark-consult (I forgot which one was which!).

> does the reordering happen if you have the cursor on a line where there's already a hint or warning ?

It happens on save and it happened independent of if there's warnings on the cursor line.

> does the reordering happen if you open consult-lsp-diagnostics after having selected a hint or a warning in a previous consult-lsp-diagnostics call ?

No, it only happens on save (as far as I see).

I'll try disabling marginalia and vertico :)

**Comment by gagbo** [comment] 2021-11-03 13:32
Marginalia won't matter, and without vertico I'm not really sure what UI you'll get, so don't worry too much about those, thanks for the answers :)

**Comment by toyboot4e** [comment] 2021-11-03 13:33
Oh I forgot to mention orderless 👀

**Comment by toyboot4e** [comment] 2021-11-03 13:38
Without orderless, reodering seems to not happen. Instead, the order is fixed as (warnings, hints, errors).

If I call `consult-lsp-diagnostics` immediately after change, there's no errors. After some seconds, they're added to the list.

**Comment by gagbo** [comment] 2021-11-03 14:49
> Instead, the order is fixed as (warnings, hints, errors)

That shouldn't happen either, so I don't think orderless is the cause either (and I use orderless as well, with `orderless-matching-styles` being `(orderless-literal orderless-regexp)`)

**Closed** 2022-03-20 11:25 UTC
